name: CI/CD Pipeline By Ranjan

on:
  push:
    branches:
      - main  # or your target branch

jobs:
  jenkins_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: 'https://351a-82-36-150-19.ngrok-free.app/job/Final-Project/'
          user: ${{ secrets.JENKINS_USERNAME }}  # Jenkins Username from Secrets
          token: ${{ secrets.JENKINS_API_TOKEN }}  # Jenkins API Token from Secrets
          job: 'Final-Project'
          insecure: false
