name: CI/CD Pipeline By Ranjan

on:
  push:
    branches:
      - main

jobs:
  jenkins_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print environment details
        run: |
          echo "Triggering Jenkins Job"
          echo "Jenkins URL: https://c0db-82-36-150-19.ngrok-free.app/job/Final-Project/build"
          echo "User: ${{ secrets.JENKINS_USERNAME }}"
          echo "Token: ${{ secrets.JENKINS_API_TOKEN }}"

      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: 'https://c0db-82-36-150-19.ngrok-free.app/job/Final-Project/build'
         
          job: 'Final-Project'
          insecure: false
