name: CI/CD Pipeline By Ranjan

on:
  push:
    branches:
      - main  # or your target branch

jobs:
  jenkins_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: 'http://192.168.0.22:8080/job/Final-Project'  
          user: ${{ secrets.JENKINS_USERNAME }}
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: 'Final-Project'

